services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      - TZ=Europe/London
      - HTTP_CONTROL_SERVER_ADDRESS=:8000
      - HTTP_CONTROL_SERVER_LOG=on
    ports:
      - 8088:8088 # QBitTorrent GUI
      - 6881:6881 # QBitTorrent Torrents
      - 6881:6881/udp # QBitTorrent Torrents
      - 8080:8080 # Sabnzbd
      - 9696:9696 # Prowlarr
    restart: unless-stopped
    privileged: true
    devices:
      - "/dev/net/tun:/dev/net/tun"

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: container:gluetun
    environment:
      - UMASK=022
      - TZ=Europe/London
      - WEBUI_PORT=8088
      - TORRENTING_PORT=6881
    volumes:
      - /volume1/docker/appdata/qbittorrent:/config
      - /volume1/data/media:/mnt/media
    restart: unless-stopped
    depends_on:
      - gluetun
  
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    network_mode: container:gluetun
    environment:
      - PUID=1026
      - PGID=100
      - UMASK=022
      - TZ=Europe/London
    volumes:
      - /volume1/docker/appdata/sabnzbd:/config
      - /volume1/data/media:/mnt/media
    restart: unless-stopped
    depends_on:
      - gluetun

  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    ports:
      - 7878:7878
    environment:
      - PUID=1026
      - PGID=100
      - UMASK=022
      - TZ=Europe/London
    volumes:
      - /volume1/docker/appdata/radarr:/config
      - /volume1/data/media:/mnt/media
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
  
  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:release
    labels:
      - org.hotio.pullio.update=${PULLIO_UPDATE}
      - org.hotio.pullio.notify=${PULLIO_NOTIFY}
      - org.hotio.pullio.discord.webhook=${PULLIO_DISCORD_WEBHOOK}
    ports:
      - 8989:8989
    environment:
      - PUID=1026
      - PGID=100
      - UMASK=022
      - TZ=Europe/London
    volumes:
      - /volume1/docker/appdata/sonarr:/config
      - /volume1/data/media:/mnt/media
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr:latest
    ports:
      - 6767:6767
    environment:
      - PUID=1026
      - PGID=100
      - UMASK=022
      - TZ=Europe/London
    volumes:
      - /volume1/docker/appdata/bazarr:/config
      - /volume1/data/media:/mnt/media
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    network_mode: container:gluetun
    environment:
      - PUID=1026
      - PGID=100
      - UMASK=022
      - TZ=Europe/London
    volumes:
      - /volume1/docker/appdata/prowlarr:/config:rw
    depends_on:
      - gluetun

  flaresolverr:
    container_name: flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest
    ports:
      - 8191:8191
    environment:
      - PUID=1026
      - PGID=100
      - UMASK=022
      - TZ=Europe/London
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
    restart: unless-stopped

  overseerr:
    container_name: overseerr
    image: ghcr.io/hotio/overseerr
    ports:
      - 5055:5055
    environment:
      - PUID=1026
      - PGID=100
      - UMASK=022
      - TZ=Europe/London
    volumes:
      - ${DOCKERCONFDIR}/overseerr:/config
      - /volume1/data/media:/mnt/media
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
